### ISSUE TITLE
在日后可能存在的多种形式的题库中，哪种将总是得到最优先的更新？

### ISSUE THREAD

**Issue by KongNan** [kessil/flaskr#2]
我也是学 python 用，那么是 data-dev.sqlite 这个吗？记得原来的题库中 data-dev.xls。

那么如果日后题库有更新，我是仅关注 data-dev.sqlite 的更新时间还是其它什么文件？ 

谢谢！

**Comment by kessil** [comment]
不再提供其他格式的题库副本，仅保留 data-dev.sqlite 作为题库唯一参考

**Comment by KongNan** [comment]
谢谢！那我就仅关注sqlite了
